version: '3.9'

services:
    rosszfogas:
        image: sebestyn/rosszfogas
        container_name: rosszfogas
        build:
            context: .
            dockerfile: ./Dockerfile
        environment:
            NODE_ENV: production
            MONGODB_URI: mongodb://database:27017/rv6jjo_rosszfogas
        restart: unless-stopped
        ports:
            - 7001:3000
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:3000']
            interval: 10s
            timeout: 5s
            retries: 2
        networks:
            - rosszfogas-network

    database:
        image: mongo
        container_name: rosszfogas_db
        volumes:
            - ./data/db:/data/db
        networks:
            - rosszfogas-network

networks:
    rosszfogas-network:
        driver: bridge
