version: '3.9'

services:
    database:
        image: mongo
        container_name: rosszfogas_db
        ports:
            - 27123:27017

    mongo-express:
        image: mongo-express
        ports:
            - 8081:8081
        environment:
            - ME_CONFIG_MONGODB_SERVER=rosszfogas_db
        depends_on:
            - database
